### ISSUE TITLE
Add support for mooks to the combat tracker

### ISSUE THREAD

**Issue by asacolips** [asacolips-projects/archmage#175]
In GitLab by @Asacolips on Mar 11, 2024, 10:43

## Summary

We have mooks as an NPC subtype, but we don't have mechanical support for them such as combining their initiative in the combat tracker or combining their HP pool.

## Rules Summary

>>>
Mooks are weaker monsters that can be cut down in large numbers in a single turn. Damage is not tracked against single mooks, but against the entire mob of mooks you’re facing. If you roll damage against a mook and it is greater than the single mook’s hit points, then another mook takes the remainder. In this way, damage can cascade to multiple mooks, and a player can kill multiple in one turn, even if they’re not all directly within your attack range.

A mook’s hit point value is one-fifth that of a regular monster.

Mooks move and attack individually. Mooks deal a fixed damage when they hit, and double damage when they roll a natural 20.

Mooks can be split up into multiple mobs with different initiative numbers and hit point pools for each.
>>>

## Technical Notes

- Ideally, the linking can happen entirely within the combat tracker. Relationships between mooks shouldn't last beyond a single combat, so that feels like the appropriate place to store the data.
- The combat tracker will also need to be extended to support mook display. My initial thought would be to show a mob as a single row in the combat tracker, but render them as an expandable row to show all of the mooks that make up the mob.
- We can't assume a mob is made up of a single type of mook, or that there will be only one mob.
- We should probably prompt for mook related stuff on the following events:
    - Mook NPC dropped onto the canvas (prompt for how many, and pull the multi-click UX from Dungeon Moon)
    - Combat started (prompt to try to guess what the possible mobs are and display those, but allow the user to customize)
    - New mook added to the initiative (prompt to guess which mob they should be added to, but allow the user to customize)
    - Mob is reduced by mook HP value (prompt to see which mook died)

## Acceptance Criteria

- [ ] Combat tracker is extended to support mook relationship data
- [ ] Combat tracker is extended to display mooks
- [ ] Prompts described above are implemented

## Labels (do-not-change)

/cc @Asacolips @cswendrowski @LegoFed3

**Comment by ben** [comment]
Having run mooks using the existing tools, I've been thinking more about this. This is all just thinking out loud, there are some parts of this that I'm not sure are feasible.

### Activation UI

The most natural way to add a bunch of tokens as a mob would be to add an option right next to how you'd add them as single combatants. Probably this only shows up if the conditions are met (all npcs, all of the same type, maybe require they all be "mook" role).

![CleanShot 2024-05-31 at 08 24 19](https://github.com/asacolips-projects/13th-age/assets/39902/93d617fb-3d0d-4367-962e-4d7336289c7e)

### Token behavior

Would it make sense to add some kind of color-coding to distinguish mob tokens? Maybe if Token Magic FX is present we can add an outline.

### Combat tracker behavior

Probably the mechanical tracker entry would be synthetic, not tied directly to a token. The UI could have a collapsible display of the individuals in the mob, but they wouldn't have their own initiative entries. (This also allows the mob to have one entry in combat carousel, which I personally would love.)

It'd be _nice_ to be able to expand that combat-tracker to show the members, but tbh I'm not sure how much use that is. Maybe it's good so you can hover over them to confirm which tokens are in the mob?

### Damage

Ideally, any damage (or healing) inflicted on any of the mob's members would be intercepted and applied to the mob's pool instead. That's probably a pre-update hook, in order to get any source of changes, like right-clicking on a damage number in a chat card, or applying it using math from the HUD, or doing it from the token-actor character sheet.

When a mook should be killed (when `Math.floor(currentMobHp / memberMaxHp)` changes), the GM should be notified. Not sure if this should be a `ui.notifications.info` or a dialog of some sort that persists longer. Also maybe as an option this could be announced to the chat? That's probably a personal preference, I use [this](https://github.com/cs96and/FoundryVTT-damage-log) and put it inline with the rest of chat.

**Comment by Mister-Nebbers** [comment]
@ben, I really love the work you were doing on [Convert to Mob](https://github.com/asacolips-projects/13th-age/pull/428). I'd benefit from the option to be able to quickly generate a dynamic number of mooks in a mob for an Actor that I can discard after the encounter is done. 

Rather than using a jumbo token to represent the mob moving as a mass, I really enjoy using Linked Tokens for a "disposable" Actor that the tracks the mob's HP in one spot, but I can still have the individual mooks represented on the map doing their own thing:
https://github.com/user-attachments/assets/be787714-3a5f-49fa-be93-a22902fec16e
<sup>A mob of mooks all taking damage after one of them is targeted</sup>

This has the problem with effects (like staggered as it was shown) getting applied to the entire mook mob, which maybe would be a deal breaker for some? Perhaps there's a not-too-complex way of suspending effects based on which token in the combat tracker received the effect? I'm not yet familiar enough the some structure, but making slow progress. I don't think things like ongoing damage would be a problem, given the shared pool anyway? Unless I'm forgetting something.

I don't have an answer or familiarity playing with this though. 
>We can't assume a mob is made up of a single type of mook

It hadn't really ever occurred to me to try making a mob with different kinds of mooks in it, but I suppose using Linked Tokens certainly wouldn't address that.

Regarding the notification for when `Math.floor(currentMobHp / memberMaxHp) ` changes, I'd prefer a mook dying being recorded to the chat.
